- name: Deploy
  hosts: vm2, vm3
  become: true
  vars:
    webserver_port: 8080
  tasks:
    - name: Install webserver packages
      apt:
        name: apache2
        state: present

    - name: Create index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Start webserver
      ansible.builtin.shell: |
        service apache2 start
        service apache2 restart

