- name: Undeploy
  hosts: vm2, vm3
  become: true
  tasks:
    - name: Stop webserver
      ansible.builtin.service:
        name: apache2
        state: stopped

    - name: Remove webserver packages
      apt:
        name: apache2
        state: absent
